/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

// VehicleTest.java
import static org.junit.Assert.*;
import org.junit.Test;

public class VehicleTest {
    @Test
    public void testCarEngineStart() {
        Car car = new Car();
        String result = car.startEngine();
        assertEquals("Car: Engine started", result);
    }
    
    @Test
    public void testBaseVehicle() {
        Vehicle vehicle = new Vehicle();
        assertEquals("Engine started", vehicle.startEngine());
    }
}
