/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

package tests.java;

import main.java.HelloWorld;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class HelloWorldTest {

    @Test
    public void testSayHello() {
        HelloWorld hw = new HelloWorld();
        String expected = "Hello World!";
        String actual = hw.sayHello();
        assertEquals(expected, actual, "The sayHello method should return 'Hello World!'");
    }
}
