/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

// RectangleTest.java
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class RectangleTest {
    @Test
    public void testDefaultConstructor() {
        Rectangle rect = new Rectangle();
        assertEquals(1, rect.calculateArea());
    }
    
    @Test
    public void testSquareConstructor() {
        Rectangle square = new Rectangle(5);
        assertEquals(25, square.calculateArea());
    }
    
    @Test
    public void testGeneralConstructor() {
        Rectangle rect = new Rectangle(4, 6);
        assertEquals(24, rect.calculateArea());
    }
}
