/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

// DrawableTest.java
public class DrawableTest {
    @Test
    public void testCircleDrawing() {
        Drawable circle = new Circle(3.5);
        assertEquals("Drawing circle with radius 3.5", circle.draw());
    }
    
    @Test
    public void testZeroRadius() {
        Drawable circle = new Circle(0);
        assertEquals("Drawing circle with radius 0.0", circle.draw());
    }
}
