/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

// BankAccountTest.java
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


public class BankAccountTest {
    @Test
    public void testInitialBalance() {
        BankAccount acc = new BankAccount(100.0);
        assertEquals(100.0, acc.getBalance(), 0.001);
    }
    
    @Test
    public void testValidWithdrawal() {
        BankAccount acc = new BankAccount(200.0);
        acc.withdraw(50.0);
        assertEquals(150.0, acc.getBalance(), 0.001);
    }
    
    @Test(expected = IllegalArgumentException.class)
    public void testOverdraftProtection() {
        BankAccount acc = new BankAccount(100.0);
        acc.withdraw(150.0);
    }
}
