/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class MathUtilityTest {
    @Test
    public void testAddTwoInts() {
        assertEquals(15, MathUtility.add(10, 5));
    }
    
    @Test
    public void testAddThreeInts() {
        assertEquals(20, MathUtility.add(5, 10, 5));
    }
    
    @Test
    public void testAddDoubles() {
        assertEquals(7.5, MathUtility.add(3.2, 4.3), 0.001);
    }
}
